[package]
name = "imgr-rust"
version = "0.2.1"
edition = "2021"
description = "Rename image files to their EXIF creation date if possible"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
kamadak-exif = "0.6"
chrono = "0.4"
walkdir = "2"
log = "0.4"
simplelog = "0.12"
indicatif = "0.17"
